services:
  order-postgres:
    container_name: order-postgres
    image: postgres:18
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderdb
    ports:
      - "5432:5432"
    volumes:
      - order-postgres-data:/var/lib/postgresql/18/docker

  user-postgres:
    container_name: user-postgres
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    ports:
      - "5433:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/18/docker

  product-postgres:
    container_name: product-postgres
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productdb
    ports:
      - "5434:5432"
    volumes:
      - product-postgres-data:/var/lib/postgresql/18/docker

  notification-postgres:
    container_name: notification-postgres
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notificationdb
    ports:
      - "5435:5432"
    volumes:
      - notification-postgres-data:/var/lib/postgresql/18/docker

  redpanda:
    container_name: redpanda
    image: redpandadata/redpanda:v26.2.3
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    ports:
      - "18081:18081"
      - "18082:18082"
      - "19092:19092"
      - "19644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  redpanda-console:
    container_name: redpanda-console
    image: redpandadata/console:v3.12.0
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "3000:8080"
    depends_on:
      - redpanda

  debezium:
    container_name: debezium
    image: quay.io/debezium/connect:3.6.3.Final
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: debezium-cdc-cluster
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    ports:
      - "8083:8083"
    depends_on:
      - order-postgres
      - redpanda

volumes:
  order-postgres-data:
  user-postgres-data:
  product-postgres-data:
  notification-postgres-data:
  redpanda-data: