syntax = "proto3";

package order.v1;

import "google/protobuf/timestamp.proto";

enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0;
  ORDER_STATUS_CREATED = 1;
  ORDER_STATUS_PAID = 2;
  ORDER_STATUS_CONFIRMED = 3;
  ORDER_STATUS_ASSEMBLING = 4;
  ORDER_STATUS_ASSEMBLED = 5;
  ORDER_STATUS_COURIER_ASSIGNED = 6;
  ORDER_STATUS_DELIVERING = 7;
  ORDER_STATUS_DELIVERED = 8;
  ORDER_STATUS_CANCELED = 9;
}

message OrderItem {
  string id = 1;
  string product_id = 2;
  string product_name = 3;
  int32 quantity = 4;
  int64 unit_price = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message Order {
  string id = 1;
  string user_id = 2;
  OrderStatus status = 3;
  repeated OrderItem items = 4;
  int64 total_amount = 5;
  string delivery_address = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}
